import { useEffect, useState, type FormEvent } from "react";
import { adminApi, routingAdminApi } from "../api";
import { useAuth } from "../auth";
import type { House, Organization, RequestItem, ResponsibilityRule } from "../types";
import { ErrorMessage } from "./UI";

export default function RoutingAdmin({ item, onUpdated }: { item?: RequestItem; onUpdated?: () => Promise<void> }) {
  const { user } = useAuth();
  const isAdmin = user.roles.includes("admin");
  const [organizations, setOrganizations] = useState<Organization[]>([]), [rules, setRules] = useState<ResponsibilityRule[]>([]), [houses, setHouses] = useState<House[]>([]), [types, setTypes] = useState<{code:string;name:string}[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [primary, setPrimary] = useState(""), [contractor, setContractor] = useState(""), [reason, setReason] = useState("Ручное назначение диспетчером");
  const [orgName, setOrgName] = useState(""), [orgType, setOrgType] = useState("MANAGEMENT_COMPANY");
  const [houseId, setHouseId] = useState(""), [organizationId, setOrganizationId] = useState(""), [category, setCategory] = useState("OTHER"), [role, setRole] = useState<ResponsibilityRule["role"]>("PRIMARY");
  async function load() { const orgs = await adminApi.organizations(); setOrganizations(orgs); if (!item && isAdmin) { const [nextRules,nextHouses,nextTypes] = await Promise.all([routingAdminApi.rules(),routingAdminApi.houses(),routingAdminApi.organizationTypes()]); setRules(nextRules); setHouses(nextHouses); setTypes(nextTypes); setHouseId((value) => value || nextHouses[0]?.id || ""); setOrganizationId((value) => value || orgs[0]?.id || ""); } }
  useEffect(() => { if (isAdmin) load().catch((e) => setError(e.message)); }, [isAdmin, item?.id]);
  if (!isAdmin) return null;
  async function manual(event: FormEvent) { event.preventDefault(); if (!item || busy) return; setBusy(true); setError(""); try { await routingAdminApi.route(item.id,{primaryOrganizationId:primary,contractorOrganizationId:contractor || undefined,reason}); await onUpdated?.(); } catch(e){setError((e as Error).message)} finally{setBusy(false)} }
  async function createOrganization(event: FormEvent){event.preventDefault();setBusy(true);setError("");try{await routingAdminApi.saveOrganization(undefined,{name:orgName,type:orgType,active:true});setOrgName("");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function createRule(event: FormEvent){event.preventDefault();setBusy(true);setError("");try{await routingAdminApi.saveRule(undefined,{houseId,organizationId,category,place:"",urgency:"",role,validFrom:new Date().toISOString(),active:true,source:"Демонстрационное правило администратора",sourceUrl:"",isDemo:true});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  if (item) return item.status === "ROUTING_REQUIRED" ? <section className="panel routing-admin"><h2>Назначить адресата</h2><form className="form" onSubmit={manual}><fieldset disabled={busy}><label>Основная организация<select required value={primary} onChange={(e)=>setPrimary(e.target.value)}><option value="">Выберите</option>{organizations.filter((o)=>o.active).map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Подрядчик<select value={contractor} onChange={(e)=>setContractor(e.target.value)}><option value="">Не назначен</option>{organizations.filter((o)=>o.active).map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Основание<textarea value={reason} onChange={(e)=>setReason(e.target.value)}/></label>{error&&<ErrorMessage message={error}/>}<button className="button primary" type="submit">{busy?"Сохраняем…":"Направить заявку"}</button></fieldset></form></section> : null;
  return <details className="panel routing-admin"><summary><strong>Организации и правила ответственности</strong></summary>{error&&<ErrorMessage message={error}/>}<div className="routing-admin-grid"><form className="form" onSubmit={createOrganization}><h3>Новая организация</h3><fieldset disabled={busy}><label>Название<input required value={orgName} onChange={(e)=>setOrgName(e.target.value)}/></label><label>Тип<select value={orgType} onChange={(e)=>setOrgType(e.target.value)}>{types.map((type)=><option key={type.code} value={type.code}>{type.name}</option>)}</select></label><button className="button" type="submit">Добавить</button></fieldset></form><form className="form" onSubmit={createRule}><h3>Новое правило</h3><fieldset disabled={busy}><label>Дом<select value={houseId} onChange={(e)=>setHouseId(e.target.value)}>{houses.map((house)=><option key={house.id} value={house.id}>{house.address}</option>)}</select></label><label>Организация<select value={organizationId} onChange={(e)=>setOrganizationId(e.target.value)}>{organizations.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label><label>Категория<input value={category} onChange={(e)=>setCategory(e.target.value)}/></label><label>Роль<select value={role} onChange={(e)=>setRole(e.target.value as ResponsibilityRule["role"])}><option value="PRIMARY">Основной адресат</option><option value="CONTRACTOR">Подрядчик</option><option value="ESCALATION">Эскалация</option></select></label><button className="button" type="submit">Создать правило</button></fieldset></form></div><div className="rule-list">{rules.map((rule)=><p key={rule.id}><strong>{rule.category}</strong> → {rule.organizationName} · {rule.role}{rule.isDemo&&" · демо"}</p>)}</div></details>;
}
