ALTER TABLE gis_house_profiles
    ADD COLUMN IF NOT EXISTS house_type_name text,
    ADD COLUMN IF NOT EXISTS house_status text,
    ADD COLUMN IF NOT EXISTS project_series text,
    ADD COLUMN IF NOT EXISTS house_condition text,
    ADD COLUMN IF NOT EXISTS lifecycle_stage text,
    ADD COLUMN IF NOT EXISTS operation_year integer,
    ADD COLUMN IF NOT EXISTS reconstruction_year integer,
    ADD COLUMN IF NOT EXISTS deterioration_percent double precision,
    ADD COLUMN IF NOT EXISTS deterioration_date date,
    ADD COLUMN IF NOT EXISTS wall_material text,
    ADD COLUMN IF NOT EXISTS energy_efficiency text,
    ADD COLUMN IF NOT EXISTS non_residential_area double precision,
    ADD COLUMN IF NOT EXISTS residential_premises integer,
    ADD COLUMN IF NOT EXISTS residential_premises_area double precision,
    ADD COLUMN IF NOT EXISTS residential_premises_with_realty integer,
    ADD COLUMN IF NOT EXISTS residential_premises_with_realty_area double precision,
    ADD COLUMN IF NOT EXISTS non_residential_premises integer,
    ADD COLUMN IF NOT EXISTS non_residential_premises_area double precision,
    ADD COLUMN IF NOT EXISTS non_residential_premises_not_common integer,
    ADD COLUMN IF NOT EXISTS non_residential_premises_not_common_area double precision,
    ADD COLUMN IF NOT EXISTS owners_or_shares integer,
    ADD COLUMN IF NOT EXISTS management_method text,
    ADD COLUMN IF NOT EXISTS management_organization_guid text,
    ADD COLUMN IF NOT EXISTS management_short_name text,
    ADD COLUMN IF NOT EXISTS management_full_name text,
    ADD COLUMN IF NOT EXISTS management_address text,
    ADD COLUMN IF NOT EXISTS management_phone text,
    ADD COLUMN IF NOT EXISTS management_website text,
    ADD COLUMN IF NOT EXISTS management_organization_type text,
    ADD COLUMN IF NOT EXISTS management_registry_organization_guid text,
    ADD COLUMN IF NOT EXISTS management_inn text,
    ADD COLUMN IF NOT EXISTS management_ogrn text,
    ADD COLUMN IF NOT EXISTS management_chief text,
    ADD COLUMN IF NOT EXISTS management_contract_start date,
    ADD COLUMN IF NOT EXISTS management_contract_end date,
    ADD COLUMN IF NOT EXISTS square_payload jsonb,
    ADD COLUMN IF NOT EXISTS square_summary_available boolean NOT NULL DEFAULT false;
