import { useEffect, useState, type FormEvent } from "react";
import { Link, NavLink } from "react-router-dom";
import { adminApi, routingAdminApi } from "../api";
import { ErrorMessage, Loading } from "../components/UI";
import { categories, type CurrentUser, type House, type Organization, type ResponsibilityRule, type UserRole } from "../types";

type Section="users"|"organizations"|"routing";
const roles:{value:UserRole;label:string}[]=[{value:"resident",label:"Житель"},{value:"manager",label:"Менеджер"},{value:"admin",label:"Администратор"}];
export default function AdminSettings({section}:{section:Section}){
  return <div className="admin-settings"><Link className="back" to="/admin">← К очереди заявок</Link><div className="eyebrow">НАСТРОЙКИ</div><h1>Администрирование</h1><nav className="admin-settings-tabs"><NavLink to="/admin/settings/users">Сотрудники</NavLink><NavLink to="/admin/settings/organizations">Организации</NavLink><NavLink to="/admin/settings/routing">Маршрутизация</NavLink></nav>{section==="users"?<Users/>:section==="organizations"?<Organizations/>:<Routing/>}</div>
}
function Users(){const [users,setUsers]=useState<CurrentUser[]|null>(null),[orgs,setOrgs]=useState<Organization[]>([]),[error,setError]=useState("");useEffect(()=>{Promise.all([adminApi.users(),adminApi.organizations()]).then(([u,o])=>{setUsers(u);setOrgs(o)}).catch(e=>setError(e.message))},[]);const replace=(u:CurrentUser)=>setUsers(v=>v?.map(x=>x.id===u.id?u:x)||null);async function role(u:CurrentUser,r:UserRole,on:boolean){try{const s=new Set(u.roles);on?s.add(r):s.delete(r);replace(await adminApi.updateUserRoles(u.id,roles.map(x=>x.value).filter(x=>s.has(x))))}catch(e){setError((e as Error).message)}}return <section className="panel admin-settings-section"><h2>Сотрудники и доступы</h2><p>Назначьте роли и организацию, заявки которой видит менеджер.</p>{error&&<ErrorMessage message={error}/>} {!users?<Loading/>:<div className="admin-users">{users.map(u=><div className="admin-user-row" key={u.id}><div><strong>{u.email||u.name}</strong><small>ID {u.id}</small></div><div className="admin-role-list">{roles.map(r=><label key={r.value}><input type="checkbox" checked={u.roles.includes(r.value)} onChange={e=>role(u,r.value,e.target.checked)}/>{r.label}</label>)}</div><label>Организация<select value={u.organizationId||""} onChange={async e=>{try{replace(await adminApi.updateUserOrganization(u.id,e.target.value))}catch(x){setError((x as Error).message)}}}><option value="">Не выбрана</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{u.roles.includes("manager")&&!u.organizationId&&<span className="admin-user-warning">Менеджеру нужна организация</span>}</div>)}</div>}</section>}
function Organizations(){const [orgs,setOrgs]=useState<Organization[]|null>(null),[types,setTypes]=useState<{code:string;name:string}[]>([]),[name,setName]=useState(""),[type,setType]=useState("MANAGEMENT_COMPANY"),[error,setError]=useState("");const load=()=>Promise.all([adminApi.organizations(),routingAdminApi.organizationTypes()]).then(([o,t])=>{setOrgs(o);setTypes(t)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);async function submit(e:FormEvent){e.preventDefault();try{await routingAdminApi.saveOrganization(undefined,{name,type,active:true});setName("");await load()}catch(x){setError((x as Error).message)}}return <section className="panel admin-settings-section"><h2>Организации</h2>{error&&<ErrorMessage message={error}/>}<form className="admin-settings-form" onSubmit={submit}><label>Название<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Тип<select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></label><button className="button primary" type="submit">Добавить организацию</button></form>{!orgs?<Loading/>:<div className="settings-list">{orgs.map(o=><article key={o.id}><strong>{o.name}</strong><span>{types.find(t=>t.code===o.type)?.name||o.type}</span><small>{o.active?"Активна":"Отключена"}</small></article>)}</div>}</section>}
function Routing(){const [rules,setRules]=useState<ResponsibilityRule[]|null>(null),[houses,setHouses]=useState<House[]>([]),[orgs,setOrgs]=useState<Organization[]>([]),[house,setHouse]=useState(""),[org,setOrg]=useState(""),[category,setCategory]=useState("*"),[place,setPlace]=useState("COMMON_PROPERTY"),[error,setError]=useState("");const load=()=>Promise.all([routingAdminApi.rules(),routingAdminApi.houses(),adminApi.organizations()]).then(([r,h,o])=>{setRules(r);setHouses(h);setOrgs(o);setHouse(v=>v||h[0]?.id||"");setOrg(v=>v||o[0]?.id||"")}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);async function submit(e:FormEvent){e.preventDefault();try{await routingAdminApi.saveRule(undefined,{houseId:house,organizationId:org,category,place,urgency:"",role:"PRIMARY",validFrom:new Date().toISOString(),active:true,source:"Правило администратора",sourceUrl:"",isDemo:false});await load()}catch(x){setError((x as Error).message)}}return <section className="panel admin-settings-section"><h2>Маршрутизация</h2><p>Точное правило категории имеет приоритет над резервным.</p>{error&&<ErrorMessage message={error}/>}<form className="admin-settings-form" onSubmit={submit}><label>Дом<select value={house} onChange={e=>setHouse(e.target.value)}>{houses.map(h=><option key={h.id} value={h.id}>{h.address}</option>)}</select></label><label>Адресат<select value={org} onChange={e=>setOrg(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Категория<select value={category} onChange={e=>setCategory(e.target.value)}><option value="*">Любая категория</option>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Место<select value={place} onChange={e=>setPlace(e.target.value)}><option value="COMMON_PROPERTY">Общее имущество</option><option value="APARTMENT">Квартира</option><option value="YARD">Двор</option><option value="RESOURCE_INPUT">Ввод ресурса</option><option value="CITY_TERRITORY">Городская территория</option></select></label><button className="button primary" type="submit">Создать правило</button></form>{!rules?<Loading/>:<div className="settings-list">{rules.map(r=><article key={r.id}><strong>{r.category==="*"?"Любая категория":categories[r.category]||r.category}</strong><span>{r.organizationName}</span><small>{r.place||"Любое место"} · {r.role}</small></article>)}</div>}</section>}
